import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import "./globals.css";

import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
import 'swiper/css/scrollbar';
import 'swiper/css/free-mode';
import 'swiper/css/thumbs';

import Link from "next/link";
import NavBar from "./components/NavBar";
import CssBaseline from "@mui/material/CssBaseline";
import { Box, Container, Fab, Toolbar } from "@mui/material";
import classNames from "classnames";
import ScrollTop from "./components/ScrollTop";
import KeyboardArrowUpIcon from "@mui/icons-material/KeyboardArrowUp";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function getLayoutData() {
  const sites: Site[] = [
    {
      key: "1",
      title: "JPL",
      url: "",
    },
    {
      key: "2",
      title: "Careers",
      url: "",
    },
    {
      key: "3",
      title: "Education",
      url: "",
    },
    {
      key: "4",
      title: "Science & Technology",
      url: "",
    },
  ];
  return {
    sites,
  };
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { sites } = await getLayoutData();
  return (
    <html lang="en">
      <body className={classNames(roboto.className, "overflow-x-hidden")}>
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <CssBaseline />
          <div className="NavDesktopTopHat z-50 px-4 bg-black lg:block relative hidden">
            <div className="container mx-auto">
              <nav
                aria-label="JPL Sites"
                className="flex items-center text-sm font-medium text-white bg-black"
              >
                {sites.map((site, idx) => (
                  <div key={site.key} className="group flex px-3">
                    <Link
                      href={site.url}
                      aria-current="page"
                      className="group nuxt-link-exact-active nuxt-link-active  cursor-pointer"
                    >
                      <span
                        className={classNames({
                          "hover:border-jpl-red-light inline-block py-2 border-b-2 border-transparent":
                            true,
                          "border-jpl-red-light": idx === 0,
                        })}
                      >
                        {site.title}
                      </span>
                    </Link>
                  </div>
                ))}
              </nav>
            </div>
          </div>
          <NavBar />
          <Toolbar id="back-to-top-anchor" className="min-h-0" />
          <main className="-mt-28">
            {children}
          </main>
          <ScrollTop>
            <Fab
              size="small"
              aria-label="scroll back to top"
              className="bg-white"
            >
              <KeyboardArrowUpIcon />
            </Fab>
          </ScrollTop>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
